//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Comment
{
    public int user_Id { get; set; }
    public int movie_Id { get; set; }
    public string comment1 { get; set; }
    public System.DateTime dateOfTheComment { get; set; }
    public int id { get; set; }

    public virtual Movie movie { get; set; }
    public virtual User user { get; set; }
}
