//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Movie
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Movie()
    {
        this.comments = new HashSet<Comment>();
        this.ratings = new HashSet<Rating>();
        this.users = new HashSet<User>();
    }

    public int id { get; set; }
    public string title { get; set; }
    public byte[] picture { get; set; }
    public int genre { get; set; }
    public Nullable<int> pg { get; set; }
    public Nullable<System.DateTime> year { get; set; }
    public string summary { get; set; }
    public Nullable<double> AVGRating { get; set; }
    public int duration { get; set; }

    public virtual Genre genre1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Comment> comments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Rating> ratings { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<User> users { get; set; }
}
